@baseUrl = http://localhost:3001

@contentType = application/json


### Create a Account

GET {{baseUrl}}/auth/sign-up
Content-Type: {{contentType}}

{
  "email": "euhenriquefranca@gmail.com",
  "password": "123456"
}